// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.Extensions.ML;
using Microsoft.ML.Data;
using Microsoft.OpenApi.Models;
using MLCategorias_WebApi.DTO;
using System.Reflection.Emit;
using static MLCategorias;

// Configure app
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddPredictionEnginePool<ModelInput, ModelOutput>()
    .FromFile("MLCategorias.mlnet");

builder.Services.AddEndpointsApiExplorer();

builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "My API", Description = "Docs for my API", Version = "v1" });
});
var app = builder.Build();

// Configuracion del swagger
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

//https://learn.microsoft.com/es-es/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-8.0&tabs=visual-studio
//Para establecer Swagger solo en Development
if (builder.Environment.IsDevelopment())
{
    app.UseSwaggerUI(options => // UseSwaggerUI is called only in Development.
    {
        options.SwaggerEndpoint("/swagger/v1/swagger.json", "v1");
        options.RoutePrefix = string.Empty;
    });
}
// Se Define el endpoint para la prediccion
app.MapPost("/api/v1/Predict",
(
    // Inyectar el pool de motores de prediccion
    PredictionEnginePool<ModelInput, ModelOutput> pool,
    //Para realizar la solicitud de prediccion
    PredictionRequestDto request
) =>
//Logica del endpoint
{
    //Si la descripcion es nula o vacia, retornar error 400
    if (string.IsNullOrWhiteSpace(request.Descripcion))
        return Results.BadRequest("Descripcion requerida");
    //Crear el input para el modelo
    var input = new ModelInput
    {
        //Tiene que ser igual al modelo del cliente
        Descripcion = request.Descripcion
    };
    //Realizar la prediccion a MlCategorias.consumption.cs, metodo Predict
    var prediction = pool.Predict(input);
    //Mapear el resultado a el response DTO
    IDictionary<string, float> scoreDict = new Dictionary<string, float>();

    var schemas = MLCategorias.PredictEngine.Value.OutputSchema;

    var labelColumn = schemas.GetColumnOrNull("Categoria");


        var keyNames = new VBuffer<ReadOnlyMemory<char>>();
        labelColumn.Value.GetKeyValues(ref keyNames);
        var categories = keyNames.DenseValues().Select(x => x.ToString()).ToArray();

    for (int i = 0; i < categories.Length; i++)
    {
        scoreDict[categories[i]] = prediction.Score[i];
    }

    //Crear el response DTO para la respuesta
    var response = new PredictionResponseDto
    {
        //Tomamos solamente la etiqueta predicha y la confianza mas alta
        Categoria = prediction.PredictedLabel,
        Confidencial = prediction.Score.Max()
        //lista de categorias en prediction.Score
        ,scoreDict = scoreDict
    };
    //Retornar la respuesta con codigo 200 que significa que todo salio bien
    return Results.Ok(response);
});


// Run app
app.Run();
